name: billing_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.1
  intl: ^0.19.0
  url_launcher: ^6.2.5
  provider: ^6.1.2
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.2
  
  # PDF & Printing
  pdf: ^3.11.1
  printing: ^5.13.3
  blue_thermal_printer: ^1.2.3
  share_plus: ^10.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pngtree-google.png
   
